import {Country} from '../../model/country';

export const countries: Country [] = [
  { code: 'AE', name: 'United Arab Emirates (the)', ext: '784' },
  { code: 'SA', name: 'Saudi Arabia', ext: '682' },
  { code: 'KW', name: 'Kuwait', ext: '414' },
  { code: 'BH', name: 'Bahrain', ext: '048' },
  { code: 'OM', name: 'Oman', ext: '512' },
  { code: 'QA', name: 'Qatar', ext: '634' },
  { code: 'AF', name: 'Afghanistan', ext: '004' },
  { code: 'AL', name: 'Albania', ext: '008' },
  { code: 'DZ', name: 'Algeria', ext: '012' },
  { code: 'AS', name: 'American Samoa', ext: '016' },
  { code: 'AD', name: 'Andorra', ext: '020' },
  { code: 'AO', name: 'Angola', ext: '024' },
  { code: 'AI', name: 'Anguilla', ext: '660' },
  { code: 'AQ', name: 'Antarctica', ext: '010' },
  { code: 'AG', name: 'Antigua and Barbuda', ext: '028' },
  { code: 'AR', name: 'Argentina', ext: '032' },
  { code: 'AM', name: 'Armenia', ext: '051' },
  { code: 'AW', name: 'Aruba', ext: '533' },
  { code: 'AU', name: 'Australia', ext: '036' },
  { code: 'AT', name: 'Austria', ext: '040' },
  { code: 'AZ', name: 'Azerbaijan', ext: '031' },
  { code: 'BS', name: 'Bahamas (the)', ext: '044' },
  { code: 'BD', name: 'Bangladesh', ext: '050' },
  { code: 'BB', name: 'Barbados', ext: '052' },
  { code: 'BY', name: 'Belarus', ext: '112' },
  { code: 'BE', name: 'Belgium', ext: '056' },
  { code: 'BZ', name: 'Belize', ext: '084' },
  { code: 'BJ', name: 'Benin', ext: '204' },
  { code: 'BM', name: 'Bermuda', ext: '060' },
  { code: 'BT', name: 'Bhutan', ext: '064' },
  { code: 'BO', name: 'Bolivia (Plurinational State of)', ext: '068' },
  { code: 'BQ', name: 'Bonaire, Sint Eustatius and Saba', ext: '535' },
  { code: 'BA', name: 'Bosnia and Herzegovina', ext: '070' },
  { code: 'BW', name: 'Botswana', ext: '072' },
  { code: 'BV', name: 'Bouvet Island', ext: '074' },
  { code: 'BR', name: 'Brazil', ext: '076' },
  { code: 'IO', name: 'British Indian Ocean Territory (the)', ext: '086' },
  { code: 'BN', name: 'Brunei Darussalam', ext: '096' },
  { code: 'BG', name: 'Bulgaria', ext: '100' },
  { code: 'BF', name: 'Burkina Faso', ext: '854' },
  { code: 'BI', name: 'Burundi', ext: '108' },
  { code: 'CV', name: 'Cabo Verde', ext: '132' },
  { code: 'KH', name: 'Cambodia', ext: '116' },
  { code: 'CM', name: 'Cameroon', ext: '120' },
  { code: 'CA', name: 'Canada', ext: '124' },
  { code: 'KY', name: 'Cayman Islands (the)', ext: '136' },
  { code: 'CF', name: 'Central African Republic (the)', ext: '140' },
  { code: 'TD', name: 'Chad', ext: '148' },
  { code: 'CL', name: 'Chile', ext: '152' },
  { code: 'CN', name: 'China', ext: '156' },
  { code: 'CX', name: 'Christmas Island', ext: '162' },
  { code: 'CC', name: 'Cocos (Keeling) Islands (the)', ext: '166' },
  { code: 'CO', name: 'Colombia', ext: '170' },
  { code: 'KM', name: 'Comoros (the)', ext: '174' },
  { code: 'CD', name: 'Congo (the Democratic Republic of the)', ext: '180' },
  { code: 'CG', name: 'Congo (the)', ext: '178' },
  { code: 'CK', name: 'Cook Islands (the)', ext: '184' },
  { code: 'CR', name: 'Costa Rica', ext: '188' },
  { code: 'HR', name: 'Croatia', ext: '191' },
  { code: 'CU', name: 'Cuba', ext: '192' },
  { code: 'CW', name: 'Curaçao', ext: '531' },
  { code: 'CY', name: 'Cyprus', ext: '196' },
  { code: 'CZ', name: 'Czechia', ext: '203' },
  { code: 'CI', name: 'Côte d\'Ivoire', ext: '384' },
  { code: 'DK', name: 'Denmark', ext: '208' },
  { code: 'DJ', name: 'Djibouti', ext: '262' },
  { code: 'DM', name: 'Dominica', ext: '212' },
  { code: 'DO', name: 'Dominican Republic (the)', ext: '214' },
  { code: 'EC', name: 'Ecuador', ext: '218' },
  { code: 'EG', name: 'Egypt', ext: '818' },
  { code: 'SV', name: 'El Salvador', ext: '222' },
  { code: 'GQ', name: 'Equatorial Guinea', ext: '226' },
  { code: 'ER', name: 'Eritrea', ext: '232' },
  { code: 'EE', name: 'Estonia', ext: '233' },
  { code: 'SZ', name: 'Eswatini', ext: '748' },
  { code: 'ET', name: 'Ethiopia', ext: '231' },
  { code: 'FK', name: 'Falkland Islands (the) [Malvinas]', ext: '238' },
  { code: 'FO', name: 'Faroe Islands (the)', ext: '234' },
  { code: 'FJ', name: 'Fiji', ext: '242' },
  { code: 'FI', name: 'Finland', ext: '246' },
  { code: 'FR', name: 'France', ext: '250' },
  { code: 'GF', name: 'French Guiana', ext: '254' },
  { code: 'PF', name: 'French Polynesia', ext: '258' },
  { code: 'TF', name: 'French Southern Territories (the)', ext: '260' },
  { code: 'GA', name: 'Gabon', ext: '266' },
  { code: 'GM', name: 'Gambia (the)', ext: '270' },
  { code: 'GE', name: 'Georgia', ext: '268' },
  { code: 'DE', name: 'Germany', ext: '276' },
  { code: 'GH', name: 'Ghana', ext: '288' },
  { code: 'GI', name: 'Gibraltar', ext: '292' },
  { code: 'GR', name: 'Greece', ext: '300' },
  { code: 'GL', name: 'Greenland', ext: '304' },
  { code: 'GD', name: 'Grenada', ext: '308' },
  { code: 'GP', name: 'Guadeloupe', ext: '312' },
  { code: 'GU', name: 'Guam', ext: '316' },
  { code: 'GT', name: 'Guatemala', ext: '320' },
  { code: 'GG', name: 'Guernsey', ext: '831' },
  { code: 'GN', name: 'Guinea', ext: '324' },
  { code: 'GW', name: 'Guinea-Bissau', ext: '624' },
  { code: 'GY', name: 'Guyana', ext: '328' },
  { code: 'HT', name: 'Haiti', ext: '332' },
  { code: 'HM', name: 'Heard Island and McDonald Islands', ext: '334' },
  { code: 'VA', name: 'Holy See (the)', ext: '336' },
  { code: 'HN', name: 'Honduras', ext: '340' },
  { code: 'HK', name: 'Hong Kong', ext: '344' },
  { code: 'HU', name: 'Hungary', ext: '348' },
  { code: 'IS', name: 'Iceland', ext: '352' },
  { code: 'IN', name: 'India', ext: '356' },
  { code: 'ID', name: 'Indonesia', ext: '360' },
  { code: 'IR', name: 'Iran (Islamic Republic of)', ext: '364' },
  { code: 'IQ', name: 'Iraq', ext: '368' },
  { code: 'IE', name: 'Ireland', ext: '372' },
  { code: 'IM', name: 'Isle of Man', ext: '833' },
  { code: 'IL', name: 'Israel', ext: '376' },
  { code: 'IT', name: 'Italy', ext: '380' },
  { code: 'JM', name: 'Jamaica', ext: '388' },
  { code: 'JP', name: 'Japan', ext: '392' },
  { code: 'JE', name: 'Jersey', ext: '832' },
  { code: 'JO', name: 'Jordan', ext: '400' },
  { code: 'KZ', name: 'Kazakhstan', ext: '398' },
  { code: 'KE', name: 'Kenya', ext: '404' },
  { code: 'KI', name: 'Kiribati', ext: '296' },
  { code: 'KP', name: 'Korea (the Democratic People\'s Republic of)', ext: '408' },
  { code: 'KR', name: 'Korea (the Republic of)', ext: '410' },
  { code: 'KG', name: 'Kyrgyzstan', ext: '417' },
  { code: 'LA', name: 'Lao People\'s Democratic Republic (the)', ext: '418' },
  { code: 'LV', name: 'Latvia', ext: '428' },
  { code: 'LB', name: 'Lebanon', ext: '422' },
  { code: 'LS', name: 'Lesotho', ext: '426' },
  { code: 'LR', name: 'Liberia', ext: '430' },
  { code: 'LY', name: 'Libya', ext: '434' },
  { code: 'LI', name: 'Liechtenstein', ext: '438' },
  { code: 'LT', name: 'Lithuania', ext: '440' },
  { code: 'LU', name: 'Luxembourg', ext: '442' },
  { code: 'MO', name: 'Macao', ext: '446' },
  { code: 'MG', name: 'Madagascar', ext: '450' },
  { code: 'MW', name: 'Malawi', ext: '454' },
  { code: 'MY', name: 'Malaysia', ext: '458' },
  { code: 'MV', name: 'Maldives', ext: '462' },
  { code: 'ML', name: 'Mali', ext: '466' },
  { code: 'MT', name: 'Malta', ext: '470' },
  { code: 'MH', name: 'Marshall Islands (the)', ext: '584' },
  { code: 'MQ', name: 'Martinique', ext: '474' },
  { code: 'MR', name: 'Mauritania', ext: '478' },
  { code: 'MU', name: 'Mauritius', ext: '480' },
  { code: 'YT', name: 'Mayotte', ext: '175' },
  { code: 'MX', name: 'Mexico', ext: '484' },
  { code: 'FM', name: 'Micronesia (Federated States of)', ext: '583' },
  { code: 'MD', name: 'Moldova (the Republic of)', ext: '498' },
  { code: 'MC', name: 'Monaco', ext: '492' },
  { code: 'MN', name: 'Mongolia', ext: '496' },
  { code: 'ME', name: 'Montenegro', ext: '499' },
  { code: 'MS', name: 'Montserrat', ext: '500' },
  { code: 'MA', name: 'Morocco', ext: '504' },
  { code: 'MZ', name: 'Mozambique', ext: '508' },
  { code: 'MM', name: 'Myanmar', ext: '104' },
  { code: 'NA', name: 'Namibia', ext: '516' },
  { code: 'NR', name: 'Nauru', ext: '520' },
  { code: 'NP', name: 'Nepal', ext: '524' },
  { code: 'NL', name: 'Netherlands (the)', ext: '528' },
  { code: 'NC', name: 'New Caledonia', ext: '540' },
  { code: 'NZ', name: 'New Zealand', ext: '554' },
  { code: 'NI', name: 'Nicaragua', ext: '558' },
  { code: 'NE', name: 'Niger (the)', ext: '562' },
  { code: 'NG', name: 'Nigeria', ext: '566' },
  { code: 'NU', name: 'Niue', ext: '570' },
  { code: 'NF', name: 'Norfolk Island', ext: '574' },
  { code: 'MP', name: 'Northern Mariana Islands (the)', ext: '580' },
  { code: 'NO', name: 'Norway', ext: '578' },
  { code: 'PK', name: 'Pakistan', ext: '586' },
  { code: 'PW', name: 'Palau', ext: '585' },
  { code: 'PS', name: 'Palestine, State of', ext: '275' },
  { code: 'PA', name: 'Panama', ext: '591' },
  { code: 'PG', name: 'Papua New Guinea', ext: '598' },
  { code: 'PY', name: 'Paraguay', ext: '600' },
  { code: 'PE', name: 'Peru', ext: '604' },
  { code: 'PH', name: 'Philippines (the)', ext: '608' },
  { code: 'PN', name: 'Pitcairn', ext: '612' },
  { code: 'PL', name: 'Poland', ext: '616' },
  { code: 'PT', name: 'Portugal', ext: '620' },
  { code: 'PR', name: 'Puerto Rico', ext: '630' },
  { code: 'MK', name: 'Republic of North Macedonia', ext: '807' },
  { code: 'RO', name: 'Romania', ext: '642' },
  { code: 'RU', name: 'Russian Federation (the)', ext: '643' },
  { code: 'RW', name: 'Rwanda', ext: '646' },
  { code: 'RE', name: 'Réunion', ext: '638' },
  { code: 'BL', name: 'Saint Barthélemy', ext: '652' },
  { code: 'SH', name: 'Saint Helena, Ascension and Tristan da Cunha', ext: '654' },
  { code: 'KN', name: 'Saint Kitts and Nevis', ext: '659' },
  { code: 'LC', name: 'Saint Lucia', ext: '662' },
  { code: 'MF', name: 'Saint Martin (French part)', ext: '663' },
  { code: 'PM', name: 'Saint Pierre and Miquelon', ext: '666' },
  { code: 'VC', name: 'Saint Vincent and the Grenadines', ext: '670' },
  { code: 'WS', name: 'Samoa', ext: '882' },
  { code: 'SM', name: 'San Marino', ext: '674' },
  { code: 'ST', name: 'Sao Tome and Principe', ext: '678' },
  { code: 'SN', name: 'Senegal', ext: '686' },
  { code: 'RS', name: 'Serbia', ext: '688' },
  { code: 'SC', name: 'Seychelles', ext: '690' },
  { code: 'SL', name: 'Sierra Leone', ext: '694' },
  { code: 'SG', name: 'Singapore', ext: '702' },
  { code: 'SX', name: 'Sint Maarten (Dutch part)', ext: '534' },
  { code: 'SK', name: 'Slovakia', ext: '703' },
  { code: 'SI', name: 'Slovenia', ext: '705' },
  { code: 'SB', name: 'Solomon Islands', ext: '090' },
  { code: 'SO', name: 'Somalia', ext: '706' },
  { code: 'ZA', name: 'South Africa', ext: '710' },
  { code: 'GS', name: 'South Georgia and the South Sandwich Islands', ext: '239' },
  { code: 'SS', name: 'South Sudan', ext: '728' },
  { code: 'ES', name: 'Spain', ext: '724' },
  { code: 'LK', name: 'Sri Lanka', ext: '144' },
  { code: 'SD', name: 'Sudan (the)', ext: '729' },
  { code: 'SR', name: 'Suriname', ext: '740' },
  { code: 'SJ', name: 'Svalbard and Jan Mayen', ext: '744' },
  { code: 'SE', name: 'Sweden', ext: '752' },
  { code: 'CH', name: 'Switzerland', ext: '756' },
  { code: 'SY', name: 'Syrian Arab Republic', ext: '760' },
  { code: 'TW', name: 'Taiwan', ext: '158' },
  { code: 'TJ', name: 'Tajikistan', ext: '762' },
  { code: 'TZ', name: 'Tanzania, United Republic of', ext: '834' },
  { code: 'TH', name: 'Thailand', ext: '764' },
  { code: 'TL', name: 'Timor-Leste', ext: '626' },
  { code: 'TG', name: 'Togo', ext: '768' },
  { code: 'TK', name: 'Tokelau', ext: '772' },
  { code: 'TO', name: 'Tonga', ext: '776' },
  { code: 'TT', name: 'Trinidad and Tobago', ext: '780' },
  { code: 'TN', name: 'Tunisia', ext: '788' },
  { code: 'TR', name: 'Turkey', ext: '792' },
  { code: 'TM', name: 'Turkmenistan', ext: '795' },
  { code: 'TC', name: 'Turks and Caicos Islands (the)', ext: '796' },
  { code: 'TV', name: 'Tuvalu', ext: '798' },
  { code: 'UG', name: 'Uganda', ext: '800' },
  { code: 'UA', name: 'Ukraine', ext: '804' },
  { code: 'GB', name: 'United Kingdom of Great Britain and Northern Ireland (the)', ext: '826' },
  { code: 'UM', name: 'United States Minor Outlying Islands (the)', ext: '581' },
  { code: 'US', name: 'United States of America (the)', ext: '840' },
  { code: 'UY', name: 'Uruguay', ext: '858' },
  { code: 'UZ', name: 'Uzbekistan', ext: '860' },
  { code: 'VU', name: 'Vanuatu', ext: '548' },
  { code: 'VE', name: 'Venezuela (Bolivarian Republic of)', ext: '862' },
  { code: 'VN', name: 'Viet Nam', ext: '704' },
  { code: 'VG', name: 'Virgin Islands (British)', ext: '092' },
  { code: 'VI', name: 'Virgin Islands (U.S.)', ext: '850' },
  { code: 'WF', name: 'Wallis and Futuna', ext: '876' },
  { code: 'EH', name: 'Western Sahara', ext: '732' },
  { code: 'YE', name: 'Yemen', ext: '887' },
  { code: 'ZM', name: 'Zambia', ext: '894' },
  { code: 'ZW', name: 'Zimbabwe', ext: '716' },
  { code: 'AX', name: 'Åland Islands', ext: '248' }
];
